import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  containerCabecalho: {
    backgroundColor: "#1A1B1C",
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 32,
    minHeight: 365,
    justifyContent: "flex-start",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  puxador: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  barraPuxador: {
    width: 40,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: "#555",
  },
  textoCabecalho: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "bold",
    letterSpacing: 0.1,
  },
  botaoAlternar: {
    position: "absolute",
    bottom: 8,
    left: 8,
    padding: 4,
  },
  campo: {
    backgroundColor: "#1A1B1C",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 16,
    color: "#ffffffff",
    borderColor: "#363636ff",
    borderWidth: 1,
  },
  campoFlexivel: {
    flex: 1,
  },
  margemDireitaPequena: {
    marginRight: 10,
  },
  linhaEntradas: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  areaTexto: {
    backgroundColor: "#1A1B1C",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 16,
    color: "#fff",
    height: 100,
    textAlignVertical: "top",
    borderColor: "#363636ff",
    borderWidth: 1,
  },
  contadorCaracteres: {
    color: "#ffffff88",
    fontSize: 12,
    textAlign: "right",
    marginTop: 4,
    marginBottom: 8,
  },
  linhaRecorrente: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 0,
    marginBottom: 0,
  },
  alternarRecorrente: {
    flexDirection: "row",
    alignItems: "center",
  },
  textoRecorrente: {
    color: "#fff",
    marginLeft: 4,
    fontSize: 16,
  },
  botoesRecorrente: {
    flexDirection: "row",
    marginTop: 8,
  },
  botaoRecorrente: {
    backgroundColor: "#444",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
    marginRight: 8,
  },
  botaoRecorrenteSelecionado: {
    backgroundColor: "#6B46C1",
  },
  textoBotaoRecorrente: {
    color: "#fff",
    fontSize: 14,
  },
  inputParcelas: {
    marginTop: 8,
  },
  linhaInferior: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 16,
  },
  alternarEntrada: {
    flexDirection: "row",
    alignItems: "center",
  },
  rotuloAlternar: {
    color: "#fff",
    marginRight: 8,
    fontSize: 16,
  },
  botaoAdicionar: {
    backgroundColor: "#6B46C1",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    marginLeft: 8,
    marginBottom: 1,
  },
  botaoAdicionarDesabilitado: {
    backgroundColor: "#555",
  },
  textoBotaoAdicionar: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
  },
});
